<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simulatefe"
 *
 * Auto generated by Extension Builder 2017-04-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simulate FE User',
    'description' => 'Based on SimulateFE by Kai Strobach, elevated to Typo3 8.x.x',
    'category' => 'plugin',
    'author' => 'Kai Strobach, Christoph Balogh',
    'author_email' => 'typo3@kay-strobach.de, cb@lustige-informatik.at',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.6.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
